### ISSUE TITLE
Call to undefined method Laravel\Lumen\Application::group()

### ISSUE THREAD

**Issue by abdullah-abunada** [kayrules/lumen-passport-mongodb#2]
Hi All,
When I run any php artisan command this error appears:

In PassportServiceProvider.php line 65:                                        
Call to undefined method Laravel\Lumen\Application::group()

**Comment by lucascardial** [comment]
Hello, @abdullah-abunada .
I made a PR #4 to fix this on my Lumen 5.7 project
