### ISSUE TITLE
Getting the {"error":"invalid_client","message":"Client authentication failed"}

### ISSUE THREAD

**Issue by morenof90** [kayrules/lumen-passport-mongodb#3]
Hi there,

I follow all the steps on the readme and i'm getting the following error: {"error":"invalid_client","message":"Client authentication failed"}

I'm sure that I'm using the correct client_id and client_secret, this is how I'm making the request in postman:
{
	"grant_type": "password",
	"client_id": "ObjectId(\"5b7486ea662c6c00aa321e62\")",
	"clien_secret": "gnBfu4isJNO41zI7ASwidLdCVSGuOoVvEYhLqm2m",
	"username":"rJBpPFBJUL@gmail.com",
	"password": "$2y$10$R3fipU2fITvyD2rJhaM.de9VHbDhbttmudSgVfU95Y7fQJ2yQVulu",
	"scope": ""
}

i tried too changing the client_id to: 5b7486ea662c6c00aa321e62 and to ObjectId(5b7486ea662c6c00aa321e62).

Yo may have some idea about what I'm doing wrong.

Thanks in advance

**Comment by lucascardial** [comment]
Your body param "client_id" be need: `"5b7486ea662c6c00aa321e62"`.
